---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: node0
    command: ${DOCKER_COMMAND:-"sleep infinity"}
    groups:
      - cassandra
      - clustered
      - ${DISTRO:-debian}${TAG:-10}
    image: ${DISTRO:-debian}:${TAG:-10}
    privileged: True

  - name: node1
    command: ${DOCKER_COMMAND:-"sleep infinity"}
    groups:
      - cassandra
      - clustered
      - ${DISTRO:-debian}${TAG:-10}
    image: ${DISTRO:-debian}:${TAG:-10}
    privileged: True

  - name: node2
    command: ${DOCKER_COMMAND:-"sleep infinity"}
    groups:
      - cassandra
      - clustered
      - ${DISTRO:-debian}${TAG:-10}
    image: ${DISTRO:-debian}:${TAG:-10}
    privileged: True

provisioner:
  name: ansible

  config_options:
    defaults:
      callback_whitelist: "profile_tasks,timer"

  inventory:
    group_vars:
      centos7:
        cassandra_systemd_enabled: True
      centos8:
        cassandra_systemd_enabled: True
        ansible_python_interpreter: python3
      debian9:
      debian10:
        cassandra_15770_workaround: True
      fedora30:
        ansible_python_interpreter: python3
        cassandra_systemd_enabled: True
      fedora31:
        ansible_python_interpreter: python3
        cassandra_systemd_enabled: True
      ubuntu18.04:
      ubuntu20.04:
        cassandra_15770_workaround: True

  log: True

  options:
    v: 1

  playbooks:
    converge: ../default/converge.yml

scenario:
  test_sequence:
    - converge
    - verify

verifier:

  name: testinfra

  directory: ../default/tests

  options:
    connection: docker
    durations: 3
    v: 1
