---
# .kitchen.yml:  Test Kitchen configuration file.
driver:
  name: docker
  use_sudo: false

platforms:
  - name: centos-7
    driver_config:
      run_command: /usr/sbin/init
      privileged: true
      platform: centos
      provision_command:
        - yum install -y epel-release
        - yum install -y gcc python2-pip rsyslog initscripts python2-devel
        - pip install ansible
        - sed -i 's/#UseDNS yes/UseDNS no/g' /etc/ssh/sshd_config
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - sed -i 's/GSSAPIAuthentication yes/GSSAPIAuthentication no/g' /etc/ssh/sshd_config
        - sed -i 's/#LogLevel INFO/LogLevel DEBUG/g' /etc/ssh/sshd_config
        - systemctl enable rsyslog.service
        - systemctl enable sshd.service

  - name: debian-9
    driver_config:
      platform: debian
      provision_command:
        - apt-get install -y apt-utils libffi-dev python-pycparser python-apt python-dev python-pip
        - pip install ansible

  - name: fedora-27
    driver_config:
      image: fedora:27
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - mkdir -p /var/run/cassandra
        - dnf install -y python3-pip rsyslog iproute yum-utils initscripts
        - pip3 install ansible
        - sed -i 's/#UseDNS yes/UseDNS no/g' /etc/ssh/sshd_config
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - sed -i 's/GSSAPIAuthentication yes/GSSAPIAuthentication no/g' /etc/ssh/sshd_config
        - sed -i 's/#LogLevel INFO/LogLevel DEBUG/g' /etc/ssh/sshd_config
        - systemctl enable rsyslog.service
        - systemctl enable sshd.service

  - name: ubuntu-16.04
    driver_config:
      platform: ubuntu
      provision_command:
        - apt-get install -y apt-utils libffi-dev python-pycparser python-apt python-dev python-pip
        - pip install ansible

provisioner:
  additional_copy_path:
    - tests
  ansible_inventory: tests/inventory
  ansible_verbose: false
  ansible_verbosity: 1
  hosts: all
  name: ansible_playbook
  require_ansible_repo: false
  require_chef_for_busser: false
  require_chef_omnibus: false
  require_pip: false
  role_name: cassandra

verifier:
  name: serverspec
  sudo_path: true

suites:
  - name: ApplyRedhat
    verifier:
      patterns:
        - tests/spec/common/*_spec.rb
        - tests/spec/redhat/*_spec.rb
    provisioner:
      idempotency_test: true
      playbook: tests/test.yml
    includes:
      - centos-7

  - name: ApplyFedora
    verifier:
      patterns:
        - tests/spec/common/*_spec.rb
        - tests/spec/redhat/*_spec.rb
    provisioner:
      idempotency_test: true
      playbook: tests/test.yml
    includes:
      - fedora-27

  - name: ApplyDebian
    verifier:
      patterns:
        - tests/spec/common/*_spec.rb
        - tests/spec/debian/*_spec.rb
    provisioner:
      idempotency_test: true
      playbook: tests/test.yml
    includes:
      - debian-9
      - ubuntu-16.04

  - name: CheckNonFedora
    provisioner:
      ansible_check: true
      playbook: tests/test.yml
    excludes:
      - fedora-27

  - name: CheckFedora
    provisioner:
      ansible_check: true
      extra_vars:
        ansible_python_interpreter: /usr/bin/python3
      playbook: tests/test.yml
    includes:
      - fedora-27
