---
# .kitchen.yml:  Test Kitchen configuration file.
driver:
  name: docker
  use_sudo: false

platforms:
  - name: fedora-28
    driver_config:
      image: fedora:28
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - dnf install -y python3-pip rsyslog
        - pip3 install ansible==2.6.0.0
        - sed -i 's/#UseDNS yes/UseDNS no/g' /etc/ssh/sshd_config
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - sed -i 's/GSSAPIAuthentication yes/GSSAPIAuthentication no/g' /etc/ssh/sshd_config
        - sed -i 's/#LogLevel INFO/LogLevel DEBUG/g' /etc/ssh/sshd_config
        - systemctl enable rsyslog.service
        - systemctl enable sshd.service

  - name: centos-7
    driver_config:
      run_command: /usr/sbin/init
      privileged: true
      platform: centos
      provision_command:
        - yum install -y epel-release
        - yum install -y gcc python2-pip rsyslog initscripts python2-devel
        - pip install ansible==2.6.0.0
        - sed -i 's/#UseDNS yes/UseDNS no/g' /etc/ssh/sshd_config
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - sed -i 's/GSSAPIAuthentication yes/GSSAPIAuthentication no/g' /etc/ssh/sshd_config
        - sed -i 's/#LogLevel INFO/LogLevel DEBUG/g' /etc/ssh/sshd_config
        - systemctl enable rsyslog.service
        - systemctl enable sshd.service

  - name: debian-9
    driver_config:
      platform: debian
      provision_command:
        - apt-get install -y apt-utils libffi-dev python-pycparser python-apt python-dev python-pip
        - pip install ansible==2.6.0.0

  - name: ubuntu-16.04
    driver_config:
      platform: ubuntu
      provision_command:
        - apt-get install -y apt-utils libffi-dev python-pycparser python-apt python-dev python-pip
        - pip install ansible==2.6.0.0

provisioner:
  additional_copy_path:
    - tests
  ansible_inventory: tests/inventory
  ansible_verbose: true
  ansible_verbosity: 1
  hosts: all
  name: ansible_playbook
  require_ansible_repo: false
  require_chef_for_busser: false
  require_chef_omnibus: false
  require_pip: false
  role_name: cassandra

verifier:
  name: serverspec
  sudo_path: true

suites:
  - name: Fedora
    verifier:
      patterns:
        - tests/spec/common/*_spec.rb
        - tests/spec/redhat/*_spec.rb
    provisioner:
      idempotency_test: true
      playbook: tests/test.yml
    includes:
      - fedora-28

  - name: Redhat
    verifier:
      patterns:
        - tests/spec/common/*_spec.rb
        - tests/spec/redhat/*_spec.rb
    provisioner:
      idempotency_test: true
      playbook: tests/test.yml
    includes:
      - centos-7

  - name: Check
    provisioner:
      ansible_check: true
      playbook: tests/test.yml

  - name: Debian
    verifier:
      patterns:
        - tests/spec/common/*_spec.rb
        - tests/spec/debian/*_spec.rb
    provisioner:
      idempotency_test: true
      playbook: tests/test.yml
    includes:
      - debian-9
      - ubuntu-16.04
