---

- name: Configure the Apache Cassandra YUM Repository
  yum_repository:
    name: cassandra
    baseurl: "https://www.apache.org/dist/cassandra/redhat/{{ cassandra_repo_apache_release }}/"
    gpgcheck: true
    description: Apache Cassandra
    repo_gpgcheck: true
    gpgkey: https://www.apache.org/dist/cassandra/KEYS
  when:
    - cassandra_configure_apache_repo|bool

- name: Install the Cassandra Package (YUM)
  # Retries are in this as the cache has been seen to still be updating when
  # this task gets to be executed.
  yum:
    name: "{{ cassandra_package }}"
    update_cache: true
  delay: "{{ cassandra_task_delay }}"
  retries: "{{ cassandra_task_retries }}"
  register: cassandra_yum_install_result
  until: cassandra_yum_install_result is succeeded
  when:
    - cassandra_install_packages|bool
    - ansible_pkg_mgr == 'yum'
    - not ansible_check_mode

- name: Install the Cassandra Package (Package)
  # Retries are in this as the cache has been seen to still be updating when
  # this task gets to be executed.
  package:
    name: "{{ cassandra_package }}"
  delay: "{{ cassandra_task_delay }}"
  retries: "{{ cassandra_task_retries }}"
  register: cassandra_pkg_install_result
  until: cassandra_pkg_install_result is succeeded
  when:
    - cassandra_install_packages|bool
    - ansible_pkg_mgr == 'dnf'
    - not ansible_check_mode
