---
version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
      - python/load-cache
      - run:
          command: |
            pyenv install 3.8.5
            pyenv version 3.8.5
            pip install -r requirements --user
          name: Install Python Packages
      - run:
          command: COMMAND="/usr/sbin/init" DISTRO="centos" TAG="8" molecule test --destroy never
          name: Default Scenario
      - run:
          command: COMMAND="/usr/sbin/init" DISTRO="centos" TAG="8" molecule test --destroy never --scenario-name combine_cluster
          name: Combine Cluster Scenario
      - python/save-cache

workflows:
  main:
    jobs:
      - build-and-test
