---
version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
      - python/load-cache
      - run:
          command: |
            pyenv versions
            pyenv local 3.5.2
            pyenv versions
            python --version
            type python
            type pip
            pip install --upgrade pip
            pip install -r requirements.txt --user
          name: Install Python Packages
      - run:
          command: COMMAND="/usr/sbin/init" DISTRO="centos" TAG="8" molecule test --destroy never
          name: Default Scenario
      - run:
          command: COMMAND="/usr/sbin/init" DISTRO="centos" TAG="8" molecule test --destroy never --scenario-name combine_cluster
          name: Combine Cluster Scenario
      - python/save-cache

workflows:
  main:
    jobs:
      - build-and-test
