---
- name: Example Playbook for the locp.ansible_role_cassandra Role

  hosts: cassandra

  remote_user: root

  vars:
    cassandra_configuration:
      authenticator: PasswordAuthenticator
      cluster_name: "{{ cassandra_cluster_name }}"
      commitlog_directory: /data/cassandra/commitlog
      commitlog_sync: periodic
      commitlog_sync_period_in_ms: 10000
      data_file_directories:
        - /data/cassandra/data
      endpoint_snitch: GossipingPropertyFileSnitch
      hints_directory: "/data/cassandra/hints"
      listen_address: "{{ ansible_default_ipv4.address }}"
      # For a sensible value to set num_tokens to, please see
      # https://cassandra.apache.org/doc/latest/getting_started/production.html#tokens
      num_tokens: 4
      partitioner: org.apache.cassandra.dht.Murmur3Partitioner
      saved_caches_directory: /data/cassandra/saved_caches
      seed_provider:
        - class_name: "org.apache.cassandra.locator.SimpleSeedProvider"
          parameters:
            - seeds: "{{ cassandra_seed }}"
      start_native_transport: true
    cassandra_configure_apache_repo: true
    # Create an alternative directories structure for the Cassandra data.
    # In this example, the will be a directory called /data owned by root
    # with rwxr-xr-x permissions.  It will have a series of sub-directories
    # all of which will be defaulted to being owned by the cassandra user
    # with rwx------ permissions.
    cassandra_directories:
      root:
        group: root
        mode: "0755"
        owner: root
        paths:
          - /data
      data:
        paths:
          - /data/cassandra
          - /data/cassandra/commitlog
          - /data/cassandra/data
          - /data/cassandra/hints
          - /data/cassandra/saved_caches
    cassandra_regex_replacements:
      - path: cassandra-env.sh
        line: 'MAX_HEAP_SIZE="{{ cassandra_max_heapsize_mb }}M"'
        regexp: '^#MAX_HEAP_SIZE="4G"'
      - path: cassandra-env.sh
        line: 'HEAP_NEWSIZE="{{ cassandra_heap_new_size_mb }}M"'
        regexp: '^#HEAP_NEWSIZE="800M"'
      - path: cassandra-rackdc.properties
        line: 'dc=DC1'
        regexp: '^dc='
      - path: cassandra-rackdc.properties
        line: 'rack=RACK1'
        regexp: '^rack='
    cassandra_repo_apache_release: 311x

  pre_tasks:
    - name: Set Variables for Clustered Nodes
      set_fact:
        cassandra_cluster_name: MyCassandraCluster
        cassandra_join_cluster: True
        cassandra_seed: "{{ hostvars[groups['cassandra'][0]]['ansible_default_ipv4'].address }}"
      when: "'clustered' in group_names"

    - name: Set Variables for Standalone Nodes
      set_fact:
        cassandra_cluster_name: Standalone
        cassandra_seed: "{{ ansible_default_ipv4.address }}"
      when: "'standalone' is in group_names"

  roles:
    - role: locp.ansible_role_cassandra

  post_tasks:
    - name: Wait for the Cassandra Listener
      wait_for:
        host: "{{ ansible_default_ipv4.address }}"
        port: 9042
      when: not ansible_check_mode

    - name: Wait for the Cassandra to Gossip
      wait_for:
        host: "{{ ansible_default_ipv4.address }}"
        port: 9160
      when: not ansible_check_mode

    - name: Wait for the Cassandra Service to be Running (Red Hat)
      service_facts:
      retries: 100
      delay: 3
      register: cassandra_services_facts
      until: cassandra_services_facts.ansible_facts.services['cassandra.service'].state == 'running'
      when:
        - not ansible_check_mode
        - ansible_os_family == 'RedHat'
        # service_facts broken for Fedora 32, fixed in Ansible 2.9.9
        # see https://bugzilla.redhat.com/show_bug.cgi?id=1832625
        - ansible_distribution_major_version != "32"

    - name: Wait for the Cassandra Service to be Running (Debian)
      service_facts:
      retries: 100
      delay: 3
      register: cassandra_services_facts
      until: cassandra_services_facts.ansible_facts.services['cassandra'].state == 'running'
      when:
        - not ansible_check_mode
        - ansible_os_family == 'Debian'
