# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN yum install -y dnf && yum clean all
RUN dnf makecache && dnf --assumeyes install sudo python3-devel python3-dnf bash && dnf clean all
