---
name: CI

on:
  pull_request:
    branches:
      - develop
  push:
    branches-ignore:
      - 'feature/latest'
      - 'main'

jobs:
  molecule:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          # Disable Tests for CentOS 7 due to https://github.com/locp/ansible-role-cassandra/issues/155
          # - image-version: centos7
          #   command: /usr/sbin/init
          #   distro: centos
          #   tag: 7
          - image-version: centos8
            command: /usr/sbin/init
            distro: centos
            tag: 8
          - image-version: debian10
            command: "sleep infinity"
            distro: debian
            tag: 10
          - image-version: debian11
            command: "sleep infinity"
            distro: debian
            tag: 11
          - image-version: fedora34
            command: "/usr/sbin/init"
            distro: fedora
            tag: 34
          - image-version: ubuntu18
            command: "sleep infinity"
            distro: ubuntu
            tag: 18.04
          - image-version: ubuntu20
            command: "sleep infinity"
            distro: ubuntu
            tag: 20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools==58.0.0 wheel
          pip install -qr requirements.txt
          pip freeze

      - name: Deploy the Initial Clusters
        env:
          COMMAND: "${{ matrix.command }}"
          DISTRO: "${{ matrix.distro }}"
          TAG: "${{ matrix.tag }}"
        run: molecule test --destroy never

      - name: Combine the Clusters
        env:
          COMMAND: "${{ matrix.command }}"
          DISTRO: "${{ matrix.distro }}"
          TAG: "${{ matrix.tag }}"
        run: molecule test --scenario-name combine_cluster
