---
name: Latest Components

on:
  push:
    branches: [ feature/latest ]
  schedule:
    - cron:  '0 0 1,15 * *'

jobs:
  molecule:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - distro: centos
            command: /usr/sbin/init
            tag: latest
          - distro: debian
            command: "sleep infinity"
            tag: stable
          - distro: fedora
            command: "/usr/sbin/init"
            tag: latest
          - distro: ubuntu
            command: "sleep infinity"
            tag: latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.X
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -qr requirements-latest.txt
        pip freeze

    - name: Test Against Latest Versions
      env:
        COMMAND: "${{ matrix.command }}"
        DISTRO: "${{ matrix.distro }}"
        TAG: "${{ matrix.tag }}"
      run: molecule test --scenario-name latest --destroy never
