---
name: Publish the Role to Galaxy

on:
  push:
    branches:
      - main

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools==58.0.0 wheel
          pip install -qr requirements.txt

      - name: Ansible Galaxy Import
        run: |
          ansible-galaxy role import --api-key "${GALAXY_API_KEY}" --branch main --role-name cassandra locp ansible-role-cassandra
        env:
          GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
